#!/usr/bin/env bash
#
# Run all dotfiles installers.

search_path="$HOME/.dotfiles"

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
  echo ''
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
  echo ''
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
  echo ''
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

info "Running all dotfiles installers."

info "Changing directory to $search_path"
cd $search_path

info "Finding installers and running them"
# find the installers and run them iteratively
find . -name install.sh | while read installer ; do info "Running installer ${installer}"; sh -c "${installer}"; success "Finished running installer '${installer}'"; done

success 'Finished running installers'
