#!/usr/bin/env bash
#
# Run all dotfiles installers.

# Includes
source "$HOME/.dotfiles/script/helpers.sh"

# Variables
search_path="$HOME/.dotfiles"

set -e

echo ''

info "Running all dotfiles installers."

info "Changing directory to $search_path"
cd $search_path

info "Finding installers and running them"
# find the installers and run them iteratively
find . -name install.sh | while read installer ; do info "Running installer ${installer}"; sh -c "${installer}"; success "Finished running installer '${installer}'"; done

success 'Finished running installers'
